dist: xenial
language: python

python:
  - 3.7

install:
  - pip install coveralls
  - pip install .[tests]
script:
  - ./test.sh
  - coverage run -m pytest
  - coverage report -m

after_success:
  - coveralls

notifications:
  email: false
