# Generated by Django 2.2.5 on 2019-09-19 15:28

from django.db import migrations, models
import friendly_states.django
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', friendly_states.django.StateField(myapp.models.TrafficLightMachine)),
                ('nullable_state', friendly_states.django.StateField(myapp.models.NullableMachine, null=True)),
                ('defaultable_state', friendly_states.django.StateField(myapp.models.DefaultableMachine, default='DefaultableState')),
            ],
        ),
    ]
